Explicitly specify Java VM to use for Maven archetype generation
Because otherwise m2e tries to detect the Java version from the pom
wich does not exist when generating from archetypes.

Prevents the following stacktrace error when creating new projects:

java.lang.IllegalArgumentException: Path must include project and resource name: /pom.xml
at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2162)
at org.eclipse.core.internal.resources.Container.getFile(Container.java:196)
at org.eclipse.m2e.internal.launch.MavenLaunchDelegate.readEnforcedJavaVersion(MavenLaunchDelegate.java:246)
at org.eclipse.m2e.internal.launch.MavenLaunchDelegate.getVMInstall(MavenLaunchDelegate.java:223)
at org.eclipse.jdt.launching.AbstractJavaLaunchConfigurationDelegate.getBootpathExt(AbstractJavaLaunchConfigurationDelegate.java:363)
at org.eclipse.jdt.launching.AbstractJavaLaunchConfigurationDelegate.getVMSpecificAttributesMap(AbstractJavaLaunchConfigurationDelegate.java:679)
at org.eclipse.jdt.launching.JavaLaunchDelegate.getVMRunnerConfiguration(JavaLaunchDelegate.java:92)
at org.eclipse.jdt.launching.JavaLaunchDelegate.launch(JavaLaunchDelegate.java:160)
at org.eclipse.m2e.internal.launch.MavenLaunchDelegate.launch(MavenLaunchDelegate.java:132)
at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:806)
at org.eclipse.scout.sdk.s2e.operation.MavenBuildOperation.scheduleMavenBuild(MavenBuildOperation.java:205)
at org.eclipse.scout.sdk.s2e.operation.MavenBuildOperation.accept(MavenBuildOperation.java:107)
at org.eclipse.scout.sdk.s2e.operation.MavenBuildOperation$M2eMavenRunner.execute(MavenBuildOperation.java:345)
at org.eclipse.scout.sdk.core.s.util.maven.MavenRunner.execute(MavenRunner.java:75)
at org.eclipse.scout.sdk.core.s.project.ScoutProjectNewHelper.createProject(ScoutProjectNewHelper.java:140)
at org.eclipse.scout.sdk.core.s.project.ScoutProjectNewHelper.createProject(ScoutProjectNewHelper.java:78)
at org.eclipse.scout.sdk.s2e.operation.project.ScoutProjectNewOperation.accept(ScoutProjectNewOperation.java:71)