Replace commons-compress with ant to extract tar archives
The new version of commons-compress requires a very up-to-date version
of commons-io. This library is already available on the classpath in
some continuous integration servers which actually hides to one from the
dependency. Unfortunately the version provided by the CI server is too
old and misses some functions required by the new Tar extractor.
As a workaround Ant is used to extract tar archives instead.

The following errors occur during Maven test execution in case the old
commons-io is available:
java.lang.NoSuchMethodError: 'long org.apache.commons.io.IOUtils.skip
(java.io.InputStream, long, java.util.function.Supplier)'