Fix incompatibility in gradle test execution
org.jetbrains.intellij.platform 2.6.0 with IJ 2024.3.3 causes:
java.lang.NoSuchFieldError: Class io.opentelemetry.semconv.ExceptionAttributes does not have member field 'io.opentelemetry.api.common.AttributeKey EXCEPTION_ESCAPED'