Require a restart on plugin update
This is required because in IJ 2020.1 the dynamic plugin reload does not
 work if plugins are dependent on each others: If plugin A is updated
 and reloaded right after IDE start and a plugin B is just being
 started, trying to use plugin A a NoClassDefFoundError might be thrown.